### ISSUE TITLE
Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.

### ISSUE THREAD

**Issue by Albert-Gao-1** [yjh0410/yolov2-yolov3_PyTorch#48]
At the begining there are some WARNs
[WARN] Cannot find rule for <class 'torch.nn.modules.container.Sequential'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'backbone.darknet.Conv_BN_LeakyReLU'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'backbone.darknet.DarkNet_19'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'utils.modules.Conv'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'utils.modules.reorg_layer'>. Treat it as zero Macs and zero Params.
[WARN] Cannot find rule for <class 'models.yolov2_d19.YOLOv2D19'>. Treat it as zero Macs and zero Params.

And it will stop at 3rd epoch and raise error when I train:
Traceback (most recent call last):
  File "train.py", line 474, in <module>
    train()
  File "train.py", line 432, in train
    dist.barrier()
  File "/home/ggy/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1959, in barrier
    _check_default_pg()
  File "/home/ggy/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 210, in _check_default_pg
    assert _default_pg is not None, \
AssertionError: Default process group is not initialized

That's my param: 
python train.py -d coco --cuda -v yolov2_d19 -hr -ms --ema

How can I solve this problem?
Thanks!

**Comment by yjh0410** [comment]
@Gangyao-01 Sorry. This is my mistake, and I have fixed it.
